### ISSUE TITLE
Works with Fira Code 3?

### ISSUE THREAD

**Issue by MrJmpl3** [kiliman/operator-mono-lig#133]
I saw the repo of Fira Code, and saw a new version: https://github.com/tonsky/FiraCode/releases/tag/3

This repo works with Fira Code 3 too?

**Comment by mskelton** [comment]
This repo is for Operator Mono, not Fira Code.  I believe Fira Code includes ligatures already, so you should be good to go.

**Comment by kiliman** [comment]
I think the confusion comes from people thinking that I simply merged the FiraCode ligatures into Operator Mono, vs creating custom ligatures. This is what tools like [Ligaturizer](https://github.com/ToxicFrog/Ligaturizer) do.

It works, but the results are not optimal as it has to scale the FiraCode ligatures to match the target metrics. Also I don't think the ligatures look as cohesive in a font as distinctive as Operator Mono. That's why all my ligatures are built with existing components. On the other hand though, FiraCode has way more ligatures than I do, so if you need those, then using other tools may be a better option.
