### ISSUE TITLE
Ligatures doesn't work after successfull build

### ISSUE THREAD

**Issue by Zeldri** [kiliman/operator-mono-lig#145]
Hi,
So as you saw on Twitter @kiliman I'm having problems with the build, I tried with the docker and the non-docker version, with all Operator-Mono fonts, and after installing the font, ligatures are not working, I'm using the preview of windows to try out the font, I know it supports ligature.
A video is better than a speech so that's what I've done :
![opmono-build-GIF](https://user-images.githubusercontent.com/30011220/89018561-59f51380-d31c-11ea-8f5d-f8a3dda4110e.gif)

In this GIF I only tried with Book Italic, but all the others are not working
I suppose the build was successfull because there were no errors during the process

**Comment by kiliman** [comment]
Are you only doing the Italic font? There was an open issue #104 about Italic ligatures.

Anyway, can you try it with the non-Italic version?

**Comment by Zeldri** [comment]
Well yes, And after trying the others, those ones work, I saw this issue before but didn't quite read it fully, so it's related only to Italic one ?
Is the problem related to the font itself ? Italic fonts ? Windows ? Or the build process, I'm asking that because I found an already converted italic one on internet, that's working on my computer, but I think it's missing Powerline glyph, or Windows Terminal is messing up with Italic fonts too, because I can't get Powerlines glyphs to work on it.

**Comment by mskelton** [comment]
Since this appears to be an issue with the italics, I'm going to close this in favor of the other two open italic related issues: https://github.com/kiliman/operator-mono-lig/issues/154 and https://github.com/kiliman/operator-mono-lig/issues/157.  Please follow those issues for progress.  There have been a lot of issues opened that have been a result of the italic problems, so I'm trying to clean things up a bit so it is less confusing about which issues are a result of the italic problem and which aren't.  Thanks for your understanding!

For reference, here is @kiliman's response in the other issue which gives some helpful context.

> Yeah, the italic version don't work all the time. Not sure why since it is built the same way. I'm working on a new method to generate the fonts that hopefully will resolve the issue.
> 
> As for the other versions of the non-SSm fonts, the main issue is lack of free time to generate the ligatures. Each font weight has to be individually updated for the 40+ ligatures. It's definitely on my TODO list.

**Comment by kiliman** [comment]
Finally got the italics to work properly. Turns out that the fonttools program allows you to import feature (.fea) files which have all the instructions on how to generate the substitution tables. No need to build my own.

This fix is in the v2.4 release https://github.com/kiliman/operator-mono-lig/releases/tag/v2.4.0

**Comment by Zeldri** [comment]
Great news :D I will check that out later on, thx for the awesome work

**Comment by kiliman** [comment]
@Zeldri have you had a chance to check out the new release? It's working fine for me on Windows.

![image](https://user-images.githubusercontent.com/47168/102512641-4393ee00-4058-11eb-8077-b5fd2f841f14.png)
