### ISSUE TITLE
Ligatures don't work in NeoVim on Konsole using the italic version.

### ISSUE THREAD

**Issue by yusi-09** [kiliman/operator-mono-lig#154]
Hello, I have successfully built this font, ligatures work in VS-Code with the tweaks that were mentioned in another issue here. But how do I get it working for the terminal, specifically Konsole? The non-italic version of the font has ligatures in the terminal and they work, but the italic version has ligatures (because the ligatures work in VS-Code) but they don't work in the terminal? Is there any way to fix this issue?

**Comment by kiliman** [comment]
The italic versions of the ligatureized font still seem to be problematic. I'm looking at trying a new method for generating the fonts that hopefully resolve this issue without any hacks. Thanks for your patience.

**Comment by kiliman** [comment]
Finally got the italics to work properly. Turns out that the fonttools program allows you to import feature (.fea) files which have all the instructions on how to generate the substitution tables. No need to build my own.

This fix is in the v2.4 release https://github.com/kiliman/operator-mono-lig/releases/tag/v2.4.0
