### ISSUE TITLE
Italics ligatures dont work in actually version but works in a older version

### ISSUE THREAD

**Issue by COD3BREAK3R** [kiliman/operator-mono-lig#157]
I refer to the issue in the next comment: https://github.com/kiliman/operator-mono-lig/issues/155#issuecomment-723184255

I also add that it is not the editor's problem because when testing the sources in the system preview there are also problems with ligatures.

![Captura de pantalla (102)](https://user-images.githubusercontent.com/51484063/100126937-94933680-2e4c-11eb-9f43-4d7be4392df1.png)

![Captura de pantalla (103)](https://user-images.githubusercontent.com/51484063/100126973-9eb53500-2e4c-11eb-86a5-98cbb1c3669a.png)

I hope this I hope this problem will be fixed and I also wish that the www ligature was included in the other variations of the font, and please, include Medium and Bold italics for no SSm fonts, in a older version exists but not in the actually:

![Captura de pantalla (104)](https://user-images.githubusercontent.com/51484063/100129142-28fe9880-2e4f-11eb-9c20-e006b1e8cb49.png)

 Thanks

**Comment by kiliman** [comment]
Yeah, the italic version don't work all the time. Not sure why since it is built the same way. I'm working on a new method to generate the fonts that hopefully will resolve the issue. 

As for the other versions of the non-SSm fonts, the main issue is lack of free time to generate the ligatures. Each font weight has to be individually updated for the 40+ ligatures. It's definitely on my TODO list.

Thanks for your patience.

**Comment by kiliman** [comment]
Finally got the italics to work properly. Turns out that the `fonttools` program allows you to import feature (`.fea`) files which have all the instructions on how to generate the substitution tables. No need to build my own.

This fix is in the v2.4 release https://github.com/kiliman/operator-mono-lig/releases/tag/v2.4.0

**Comment by kufii** [comment]
@kiliman it works! very exciting since this hasn't working since I first started using operator-mono-lig. Great job!

**Comment by COD3BREAK3R** [comment]
> Finally got the italics to work properly. Turns out that the `fonttools` program allows you to import feature (`.fea`) files which have all the instructions on how to generate the substitution tables. No need to build my own.
> 
> This fix is in the v2.4 release https://github.com/kiliman/operator-mono-lig/releases/tag/v2.4.0

Ligatures italics work in Windows but not in VS Code, some idea for what reason not working in VS Code?  

![Captura de pantalla (110)](https://user-images.githubusercontent.com/51484063/105411354-4b1f5780-5c01-11eb-9233-78502e2425b2.png)

![code](https://user-images.githubusercontent.com/51484063/105411366-507ca200-5c01-11eb-9345-0e21d8922764.png)

**Comment by kiliman** [comment]
Hmm... not sure why it's not working for you in VS Code. All the italic ligatures show properly for me on Windows.

Did you uninstall and reinstall the font? What is your VS Code font settings.

![image](https://user-images.githubusercontent.com/47168/105417239-5080a000-5c09-11eb-8568-495b298277ed.png)

**Comment by COD3BREAK3R** [comment]
The ligatures already work correctly, it was yesterday that I uninstalled them, then today after turning on the computer I run the build.bat file and installed the fonts again and they already work. Thanks for creating this project

> Hmm... not sure why it's not working for you in VS Code. All the italic ligatures show properly for me on Windows.
> 
> Did you uninstall and reinstall the font? What is your VS Code font settings.
> 
> ![image](https://user-images.githubusercontent.com/47168/105417239-5080a000-5c09-11eb-8568-495b298277ed.png)
