### ISSUE TITLE
Got a lot of errors after npm install. (Windows 11)

### ISSUE THREAD

**Issue by amlxv** [kiliman/operator-mono-lig#179]
![](https://i.imgur.com/ePW32dd.png)

![](https://i.imgur.com/mG3vd6L.png)

**Comment by kiliman** [comment]
Is this with the latest version? If not, can you delete the package.lock.json file and try again?

**Comment by amlxv** [comment]
Sure. It's the latest version. 

When I looked at those errors, some of them are showing `C:\GTK\...` but I didn't have that directory.

**Comment by toplinuxsir** [comment]
I am facing the same problem when build for windows 11

**Comment by kiliman** [comment]
So weird. I just did a fresh clone and install and everything went fine.

<img width="735" alt="image" src="https://user-images.githubusercontent.com/47168/154704741-c3708da3-f27f-4de0-b5ab-ee4e37d62f02.png">

Are you installing from Releases instead of `git`?

Anyway I also updated the Releases, so please try v2.4.2 and let me know if this solves the problem.

**Comment by amlxv** [comment]
> Anyway I also updated the Releases, so please try v2.4.2 and let me know if this solves the problem.

Amazing! Now it's work. Thank you.
