### ISSUE TITLE
Is Glyph the only program you can do this with?

### ISSUE THREAD

**Issue by Orillian** [kiliman/operator-mono-lig#31]
I don't own a Mac and I was going to try my hand and making some of the PHP ligatures to help out, but I'm kinda new to this font editing stuff, I've looked at a few applications, but I'm uncertain what the app needs to be able to do to to export the xml's you are using...thoughts?

**Comment by kiliman** [comment]
I originally used FontForge, an open source font editor. https://fontforge.github.io/en-US/

Basically, I edit the fonts and save it as OTF. Put the .otf file in the `ligature_source` folder, then run `extract`. It will then generate the XML files for you.

If you're going to add a new ligature, you need to do a few things:

1) When you name the glyph, use the format: 'glyph1_glyph2_glyph3.liga' where each glyph is the component name, like 'equal_greater.liga'
2) Make sure the width is a multiple of 550 for the normal OM font and 625 for ScreenSmart. So if you have a ligature of 3 characters, it will be 3 * 550 = 1650 or 3 * 625 = 1875. 
3) I typically try to set my LSB (Left-Side Bearing) to 87 and then stretch and make the RSB 87 as well. If you're making a glyph like `&&` or `??`, then I typically center the glyph. Sometimes you'll want to "optically" center instead of mathematically center. That is, move the glyph around until it looks balanced on both sides. Curves and slants tend to fool the eye. The Glyphs app had a nice feature where you can add text around the glyph so you could see it better in context. Check out the YouTube video from the README to see what I mean.

You'll also need to do the following outside the font editor:

1) Update the file `/ligatures/glyphs.xml` and add your new glyphs. Don't worry about the id, they'll be renumbered when building the new font. Just make it the next sequence.
2) Update the file `/ligatures/lookup.xml` to add your ligature mapping. Look for the first character in your glyph (like `equal` and find the corresponding `<LigatureSet glyph="equal">`. Add a new `<Ligature/>` entry, where `components="..."` the remaining characters (comma separated for multiple). NOTE: Make sure you order them with the longest sequence first as the first match will be the one that is displayed.

This is just a quick summary off the top of my head. One of the issues is that the extract and build tools expect all ligatures be present in each font weight. That's why I've been slow to add new ligatures for now. You can also run extract and build scripts by passing in the font name: `build OperatorMonoLig-Book` to build individual fonts.

Anyway, if you have any questions, post them here and I'll try to answer.

**Comment by Orillian** [comment]
Awesome. Thanks for the directions. I'll start fiddling around with this this weekend!
