### ISSUE TITLE
Problem with ./build.sh

### ISSUE THREAD

**Issue by j-jeudesprit** [kiliman/operator-mono-lig#32]
Added the fonts in "original" folder https://imgur.com/a/IPa7o
Installed this  "pip3 install fonttools";
node -v ~ v9.2.0, npm -v  ~ 5.5.1;
npm install;
But, when i put run "./build.sh" - nothing happens. 
No errors, "build" folder is empty. 
What am I doing wrong?
macOS HighSierra 10.13.1

**Comment by kiliman** [comment]
I have seen this a couple of times before. The reason is that your font names don't match what the script is expecting.

All my fonts look like this:

OperatorMono-Book, OperatorMono-BookItalic, etc.

NOTE: No spaces and hyphen separating front name from style.

Rename your files and it should work.

**Comment by j-jeudesprit** [comment]
Thx.

**Comment by kiwinut** [comment]
How are Operator SSm fonts supposed to be named then? I'm having the same issue.
