### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by sdyrby** [kiliman/operator-mono-lig#39]
Hi I keep getting the following error, both on win10 and osx.

```/Users/sd/Downloads/operator-mono-lig-master/index.js:20
async function main() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

My font names are as follows:
```
OperatorMono-Bold.oft
``` 
.. and so on.

What am I doing wrong? Thanks

**Comment by kiliman** [comment]
The script uses `async/await` so you'll need to make sure you have Node.js v7.6 or higher.

**Comment by sdyrby** [comment]
Offtopic. Any support for the Light version of the font?

**Comment by kiliman** [comment]
Not yet, but that's on the todo list. Do you have the ScreenSmart version or the regular, so I can at least prioritize?

**Comment by Orillian** [comment]
@sdyrby This is an issue with the original font in certain editors. I'm not sure why this happens, but for example in LibreOffice Writer they look fine, but when using them in phpStorm I see the same thing as you.

LibreOffice Writer
![op-mono-libre](https://user-images.githubusercontent.com/823192/35289766-883d1174-0025-11e8-9741-c4671be25723.png)

Op Mono Book no ligatures.
![op-mono-phpstorm](https://user-images.githubusercontent.com/823192/35289769-8a6a3bca-0025-11e8-8f5e-a04d2a7b0b11.png)

**Comment by kiliman** [comment]
If you look at the CharStrings for Operator Mono (non ScreenSmart), you'll notice that all the coordinates are floating point. The ScreenSmart versions are all integers.

I have a feeling that some rasterizers may have rounding issues with the floating point coordinates at smaller pixel sizes.

Since this tool only adds ligatures to the existing fonts, it shouldn't alter the glyphs at all.

I'm assuming you resolved the Syntax Error, so I'm going to close this issue.
