### ISSUE TITLE
Whitespace looks weird

### ISSUE THREAD

**Issue by mixj93** [kiliman/operator-mono-lig#42]
whitespace looks shrinked and narrower than usual.

![image](https://user-images.githubusercontent.com/12998118/35909722-5a3338f6-0c2f-11e8-9561-5edc316becdc.png)

it looks fine in Operator Mono Lig, but werid in Operator Mono SSm Lig

**Comment by kiliman** [comment]
Are you sure that's Operator Mono? That doesn't look like mono-spaced, otherwise all the characters would line up in columns. Looks like you patched the regular Operator font.

![image](https://user-images.githubusercontent.com/47168/35921950-2c76dc46-0bea-11e8-8a09-9b95f74b2ed7.png)

Here's the same code using Operator Mono SSm Lig Book

![image](https://user-images.githubusercontent.com/47168/35918530-20010ffe-0be0-11e8-85bf-623aea327c17.png)
