### ISSUE TITLE
Request to fix operators

### ISSUE THREAD

**Issue by jakehamilton** [kiliman/operator-mono-lig#45]
First off, thank you so much @kiliman for the amazing work thus far!!!

I'd like to throw in the suggestion to include/fix some operators here:

+ `<|>` currently displays as the left pipeline and greater than
+ `&&&` currently displays as a combined `&&` followed by one more disjointed `&`

And to echo issue #36:

+ `>>=` displays as a greater than followed by a greater-than-or-equal symbol
+ `=<<` displays as a less-than-or-equal followed by a less than symbol

I plan on grabbing the trial of [Glyphs](https://glyphsapp.com/) to play around, but I doubt I'll end up with anything as solid as the work you've already done ^_^.

Thanks again!

**Comment by kiliman** [comment]
Hi thanks for the nice comments. I hope to include more of the ligatures from Fira Code. I've also read up on conditional substitutions in OpenType, so the font should be smarter about when to render a glyph.

Glyphs is a pretty cool app. If you have any questions let me know. You can also use Glyphs Mini. With a coupon code you can get it for like $29.

Good luck!

**Comment by kiliman** [comment]
The ligatures have been fixed in the new branch features/contextsubst. By using the context substitution feature of OpenType, you will no longer get invalid ligature combinations.

NOTE: This only includes the Operator Mono ScreenSmart Book and Book Italic versions. This update was mainly for testing the new build process.
