### ISSUE TITLE
Add >>= ligature

### ISSUE THREAD

**Issue by donut** [kiliman/operator-mono-lig#61]
`>>=` is really common in OCaml and Haskell. [Hasklig](https://github.com/i-tu/Hasklig) has [a nice example](https://github.com/i-tu/Hasklig#hasklig) of this. Otherwise, it looks weird with just the `>` next to the `>=` ligature:

<img width="112" alt="screen shot 2018-05-25 at 11 12 16" src="https://user-images.githubusercontent.com/37392/40559698-82ae67a2-600c-11e8-83e4-fa35e8d52939.png">

[Fira Code](https://github.com/tonsky/FiraCode) also has a very nice ligature for this:

<img width="120" alt="screen shot 2018-05-25 at 11 14 02" src="https://user-images.githubusercontent.com/37392/40559811-d2ff8ba0-600c-11e8-830d-6b509db49c15.png">

**Comment by kiliman** [comment]
If you have the Operator Mono ScreenSmart Book weight, you can get these ligatures right now. Switch to the branch `features/contextsubst` and build from there. This branch contains a whole new process for building the ligatures, and all they glyphs were redone. You can even customize which glyphs to include/exclude as well as substitute from alternate glyphs. I just haven't had time to write up documentation or work on other weights, that's why I haven't merged it to the master branch yet.

Anyway, here's what the glyph would look like in Code.

![image](https://user-images.githubusercontent.com/47168/40565676-727871aa-603b-11e8-85eb-a625079042b9.png)

**Comment by donut** [comment]
Unfortunately, I don't have the ScreenSmart variation. I'll keep an eye out for when/if it makes it to the non-SSM versions. Thanks! I'm really enjoying having code ligatures with this font.

**Comment by kiliman** [comment]
This is in v2.0, but only for ScreenSmart. I'm soliciting help for updating all the other fonts.
