### ISSUE TITLE
Improper Ligatures In Comments

### ISSUE THREAD

**Issue by google-mac** [kiliman/operator-mono-lig#82]
All ligatures seem to be working properly for me except for those in the comments. There is duplication of characters, misspacing, and sometimes removal of characters like a quote.

I use MacVim.

I wouldn't mind turning off ligatures for comments if that was an option. Fira Code (iScript) does not support it in the comments, so I'm used to that.

I also saw https://github.com/kiliman/operator-mono-lig/issues/2 but that had no way I could see to specify "only in comments".

<img width="1289" alt="TextConversationController_php______Code_php_brightphone_brightphone_app_Http_Controllers_Admin_TextAutomation__-_VIM" src="https://user-images.githubusercontent.com/17652149/55571422-561a9800-56ba-11e9-8b27-3c934282d7e7.png">

<img width="1067" alt="TextConversationController_php______Code_php_brightphone_brightphone_app_Http_Controllers_Admin_TextAutomation__-_VIM 2" src="https://user-images.githubusercontent.com/17652149/55571428-5a46b580-56ba-11e9-9f4d-f6ebb084a535.png">

**Comment by kiliman** [comment]
I don't use MacVim, so I installed it to see what it looks like.
When I use the HTML file type, this is what it renders as:
![image](https://user-images.githubusercontent.com/47168/55588129-f85a7000-56fa-11e9-9f35-cb5da045b93b.png)

Notice that anywhere it's italic, it doesn't show ligatures at all. NOTE: This is my updated version of the ligatures (currently only available in Operator Mono SSm Book)

But when I use the older version, I get odd spacing issues (there should be spaces after the arrow)

![image](https://user-images.githubusercontent.com/47168/55588836-d19d3900-56fc-11e9-9e09-88dec9e94a81.png)

Anyway, not sure what's causing the issues. The new font works correctly except for italics. I can't compare with Fira Code since it doesn't have italics.

Anyway, not sure what to say.

**Comment by google-mac** [comment]
That makes sense. So do you know if there's a way to disable italics? That would solve the issue.

**Comment by kiliman** [comment]
Perhaps a temporary workaround is to just build an italic version without ligatures. That way you can still have comments and stuff in italic, but the ligatures won't mess up.

**Comment by google-mac** [comment]
I actually want the ligatures- I don't care if italics are enabled.

**Comment by kiliman** [comment]
As a comparison, here's how it looks in VS Code

![image](https://user-images.githubusercontent.com/47168/55589634-b92e1e00-56fe-11e9-8b99-c34c9944aef3.png)

As for comments in italic, I would search for how to edit themes in MacVim. That's what is enabling the italics.

**Comment by google-mac** [comment]
I looked that up and found that I need to set `g:onedark_terminal_italics=0` which turned italics off. Unfortunately that did not resolve the issues.

**Comment by kiliman** [comment]
Which version of Operator Mono are you using? Do you have ScreenSmart?

**Comment by google-mac** [comment]
I do not have ScreenSmart, unfortunately. I also don't remember the version.

**Comment by kiliman** [comment]
Email me at kiliman@gmail.com. I'll send you a version for you to test. Thanks.

**Comment by google-mac** [comment]
Thanks for helping me out!
