### ISSUE TITLE
Is it possible to replace the % symbol ? It is too tiny for me

### ISSUE THREAD

**Issue by cata0309** [kiliman/operator-mono-lig#85]

**Comment by kiliman** [comment]
I don't currently have a way to replace existing glyphs, but I will take a look at adding that feature.

I agree, the % symbol is odd with its closed circles.

**Comment by cata0309** [comment]
Thank you very much @kiliman ! Please reply here when you will replace, I can't see another way of being updated with the news from you.

**Comment by cata0309** [comment]
Have you done any changes to the % gliph ? Let me know please !

**Comment by kiliman** [comment]
How does this look?

![image](https://user-images.githubusercontent.com/47168/61482694-3c4f4900-a969-11e9-85aa-3255b2e57d77.png)

**Comment by cata0309** [comment]
The first one looks awesome !! Very balanced with the digits, the second one is difficult to distinguish right away. The first is the good choice.

**Comment by kiliman** [comment]
Ha. The 2nd one is the current Operator Mono one. I was just showing it in comparison.

Not a big fan of the closed circles, so I see why you would like a replacement.

**Comment by cata0309** [comment]
Thank you, @kiliman :))

**Comment by kiliman** [comment]
Here's what the alternate % sign looks like in VS Code.

![image](https://user-images.githubusercontent.com/47168/61750459-778bb680-ad73-11e9-80d6-c4a5216bc866.png)

I have added support in latest build on branch `features/contextsubst`. This allows replacing existing glyphs with alternates. 

Since the alternate percent glyph is optional, you will need to add a custom `profiles.ini` file in the `./original` folder. This is how you can define custom fonts.

```ini
[default]
percent=percent.alt
```

The format of the `profiles.ini` file is:

```ini
# optional comments
[profile]
# map glyph to an alternate
glyph=altglyph
# don't add this glyph to the font
!glyph
```

You can have more than one profile. The profile name is appended to the name of the font (except for default). This way you can create different fonts with different ligatures, etc. for specific languages. So if you have a `[Go]` profile, the font would be _Operator Mono SSm Lig Go_.

You can also disable certain ligatures if you want. For example, if you don't like the == glyph, just add: `!equal_equal.liga`

If you want to try the alternate ligatures, you can do: `less_equal.liga=less_equal.2.liga`

Look in the glyphs folder to see what alternates are available.

Let me know if you have any questions.

**Comment by kiliman** [comment]
Closed by 2de4cec227ea2971ebefd8665ad2d9792eb7d5d0 and 094662aef66d0a2072127b9865c30f557b928435

**Comment by cata0309** [comment]
Thank you @kiliman

**Comment by kiliman** [comment]
Please use the `develop` branch. I've merged the feature branch and deleted it.

**Comment by cata0309** [comment]
I will

mie., 24 iul. 2019, 17:07 Kiliman <notifications@github.com> a scris:
