### ISSUE TITLE
less_slash is slighter lower than regular greater than

### ISSUE THREAD

**Issue by urielzen** [kiliman/operator-mono-lig#98]
**Operator Mono Lig Light**
At default zoom in VSCode in Windows the less_slash is slighter lower than regular greater than. It is hard to see, but it is about a pixel lower at this zoom.

![image](https://user-images.githubusercontent.com/7947179/62427563-71260480-b6ba-11e9-8227-a2acc603856d.png)

![image](https://user-images.githubusercontent.com/7947179/62427574-a16da300-b6ba-11e9-848f-f87ad3e9626d.png)

Same thing for the slash_greater and the regular less than.
![image](https://user-images.githubusercontent.com/7947179/62427539-26a48800-b6ba-11e9-90c8-98998137798f.png)

![image](https://user-images.githubusercontent.com/7947179/62427584-b77b6380-b6ba-11e9-9c79-85a93dac2785.png)

**Comment by kiliman** [comment]
Thanks for pointing out these issues. I'll take a look and see if it's an easy fix.

**Comment by kiliman** [comment]
Sorry for the delay. Here's what it looks like on Mac and Windows. As you can see, I don't have the issues you're having. Can you clear out the build folder and regenerate the files and let me know if you still have this issue? What happens if you change the font size?

Mac OS
Operator Mono Lig Light
Font Size: 14px (default)

![image](https://user-images.githubusercontent.com/47168/66160662-9bcc0500-e5f8-11e9-9d08-e355d0bd7aa7.png)

Windows 10
Operator Mono Lig Light
Font Size: 14px (default)

![image](https://user-images.githubusercontent.com/47168/66160610-81922700-e5f8-11e9-9949-ed840fb2731d.png)

**Comment by urielzen** [comment]
No worries, this was just nitpicking too much. Thanks a lot for you all your work.
